server:
  port: 9002
spring:
  application:
    name: microservice-movie
#配置Eureka 客戶端註冊訊息
eureka:
  client:
    register-with-eureka: false #作為客戶端需要註冊到Eureka
    fetch-registry: true #作為客戶端需要從Eureka獲取註冊訊息
    service-url: #客戶端註冊地址
      defaultZone: http://127.0.0.1:8888/eureka,http://127.0.0.1:9999/eureka
    registry-fetch-interval-seconds: 5 #修改提供方獲取註冊訊息的時間
  instance:
    prefer-ip-address: true #優先使用該服務的IP地址註冊到Eureka，在實際生產環境建議改為true

#開啟openFeign熔斷器
feign:
  hystrix:
    enabled: true
#修改Ribboon負載平衡演算法
microservice-user:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

